# -*- coding: utf-8 -*-
"""audioToTextHuggingFace.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1EarmMmamZrPB8SE9Ix_97Tw1h_ZxWREI
"""

!pip install -q transformers

import librosa
import torch
from transformers import Wav2Vec2ForCTC , Wav2Vec2Tokenizer

tokenizer = Wav2Vec2Tokenizer.from_pretrained('facebook/wav2vec2-base-960h')
model = Wav2Vec2ForCTC.from_pretrained('facebook/wav2vec2-base-960h')

speech,rate = librosa.load('/content/fun-in-osaka_Ck8Pwxzm.mp3',sr=16000)

rate

import IPython.display as display
display.Audio('/content/fun-in-osaka_Ck8Pwxzm.mp3',autoplay=True)

input_values = tokenizer(speech,return_tensors ='pt').input_values

input_values

logits = model(input_values).logits

logits

predicted_ids = torch.argmax(logits,dim = -1)

transcriptions = tokenizer.decode(predicted_ids[0])

print(transcriptions)











